"""Fix field in BaseField model

Revision ID: d88241343583
Revises: 84152584b762
Create Date: 2024-10-28 11:07:43.570487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88241343583'
down_revision: Union[str, None] = '84152584b762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('upd_date')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upd_date', sa.DATETIME(), nullable=False))
        batch_op.drop_column('update_date')

    # ### end Alembic commands ###
